### PR TITLE
Update gradle to enable macOS ARM builds

### PR DESCRIPTION
**Pull request by noamzaks**

### CODE REVIEW

**Comment by noamzaks** [comment]
From what I understand, GitHub Actions doesn't have macOS ARM runners yet, so I'm guessing the workflow can't be used to automatically publish builds for macOS ARM. Unless we could cross-compile with Xcode or something of the sort...

**Comment by calcmogul** [comment]
We won't be supporting macOS ARM until there are GitHub Actions runners for it.

**Comment by noamzaks** [comment]
Makes sense. In any case, I believe this is needed for the build to work on macOS ARM (in the future)

**Comment by ThadHouse** [comment]
Yeah there will be a lot more then this required in the future. Also instead of removing the wrapper task change it to match the other updated repos. And make sure there is a new line at eof.

But TBH since more changes will be required, I'd probably rather do it all in 1 change. And this isn't something that would get merged until we start adding m1 support officially, as we don't want to break anything.

**Pull request closed without merging**
