### PR TITLE
Build OpenCV with FFmpeg and x264

### PR DESCRIPTION
**Pull request by nathanmutin**

### CODE REVIEW

**Comment by PeterJohnson** [comment]
It’s not quite this easy, due to cross builds.  We have to install the right libraries for each target.  We also have to look at how this impacts downstream projects’ linkage.

**Comment by nathanmutin** [comment]
@PeterJohnson , do I need to save the ffmpeg libs files (.a) in the archive ?

**Comment by nathanmutin** [comment]
Has this PR a chance of being merged one day or do I need to abandon it ?

**Comment by PeterJohnson** [comment]
It definitely does.  We want ffmpeg for h264 support, but we will need libx264 added to this build as well.

**Comment by nathanmutin** [comment]
Ok nice but we have an issue with the build : it takes more than an hour and azure doesn't like that. Adding an other dependency will be complicated I think.

**Comment by nathanmutin** [comment]
Ok I adding h264 support shouldn't be to difficult :
- For Windows : OpenCV FFmpeg prebuilt binaries are supporting h264 : [opencv/opencv/3rdparty/ffmpeg/readme](https://github.com/opencv/opencv/blob/master/3rdparty/ffmpeg/readme.txt)
- For Linux and Mac doing the same way as ffmpeg should work

**Comment by nathanmutin** [comment]
@PeterJohnson is it possible for you to trigger a new macos build ? The last one has failed because of a 404 error during the install step and I want to know if I have solved a problem with Mac.

**Comment by sciencewhiz** [comment]
you can add `timeoutInMinutes: 0` to the failing sections of azure-pipelines.yml. This will let it run the maximum (currently 6 hours).

**Comment by PeterJohnson** [comment]
Closing in favor of wpilibsuite/thirdparty-ffmpeg repo.  We aren't going to try to build opencv with ffmpeg support, but rather use ffmpeg directly.  Thanks for all your hard work on this, much of it was reused for thirdparty-ffmpeg.

**Pull request closed without merging**
